// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Direct (non-pooled) connection: the Prisma CLI (migrate/studio) needs
    // this instead of the pooled DATABASE_URL used by the app at runtime.
    url: process.env["DIRECT_URL"],
  },
});
